# https://cert-manager.io/docs/usage/certificate/
apiVersion: cert-manager.io/v1
kind: Certificate

spec:
  secretName: ods-elon-edu-tls
  name: ods-elon-edu-tls

  duration: 2160h
  renewBefore: 360h
  
  commonName: ods.elon.edu

  subjects:
    organizations:
      - Elon University
    pronvinces: 
      - North Carolina
    countries: 
      - US
  privateKey:
    algorithm: ECDSA
    rotationPolicy: Always
  usages:
    - server auth
    - client auth

  dnsNames:
    - ods.elon.edu
    - api.ods.elon.edu
    - stats.ods.elon.edu

  issuerRef:
    name:  incommon-production
    kind: ClusterIssuer

